services:
  mariadb:
    image: mariadb:10.11
    container_name: postfixadmin-db
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: postfix
      MARIADB_USER: postfix
      MARIADB_PASSWORD: postfixPassword
    ports:
      - "3306:3319"
    healthcheck:
      test: ["CMD", "mariadb-admin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  postfixadmin:
    image: jniltinho/go-postfixadmin:latest
    container_name: postfixadmin-app
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_DRIVER: mysql
      DB_URL: postfix:postfixPassword@tcp(mariadb:3306)/postfix?charset=utf8mb4&parseTime=True&loc=Local&multiStatements=true
      ADMIN_EMAIL: admin@example.com
      ADMIN_PASSWORD: adminpassword
    ports:
      - "8080:8080"
    volumes:
      - ./config.toml.example:/app/config.toml
